In a Simple / Basic RNN, it is all about implementing the following equation

$Y_t = f( X_t . W_x +  Y_{t-1} . W_y  + b )$

In [1]:
import numpy as np
import tensorflow as tf
import os
from datetime import datetime

In [2]:
n_inputs = 3
n_neurons = 5
n_steps = 2

In [3]:
X = tf.placeholder(tf.float32, [None, n_steps, n_inputs], name='X')
seq_length = tf.placeholder(tf.int32, [None], name='seq_length')

basic_cell_fw = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
basic_cell_bw = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)

outputs, states = tf.nn.bidirectional_dynamic_rnn(basic_cell_fw, basic_cell_bw, X, sequence_length=seq_length, dtype=tf.float32)
conc_outputs = tf.concat(outputs, 2, name='conc_outputs')


In [4]:
now = datetime.utcnow().strftime("%Y-%m-%d-%H:%M:%S")
root_logdir = "tf_logs"
logdir = os.path.join(os.getcwd(),"{}/run-{}".format(root_logdir, now))

file_writer = tf.summary.FileWriter(logdir, tf.get_default_graph())

In [5]:
init = tf.global_variables_initializer()
# Mini-batch
X_batch = np.array([
    # step 0   step 1
    [[0,1,2],[9,8,7]], # instance 0
    [[3,4,5],[0,0,0]], # instance 1
    [[6,7,8],[6,5,4]], # instance 2
    [[9,0,1],[3,2,1]]  # instance 3
])

seq_length_batch = np.array([2,1,2,2])

sess = tf.InteractiveSession()
init.run()
np_outputs, np_states, np_conc_outputs = sess.run([outputs, states, conc_outputs], feed_dict={X:X_batch, seq_length:seq_length_batch})
sess.close()
file_writer.close()

In [6]:
np_outputs

(array([[[-0.90247554,  0.71488017, -0.67150509, -0.69992298, -0.48467708],
         [-0.97520906,  0.98924893,  0.97816467, -0.99993235,  0.96553952]],
 
        [[-0.98945618,  0.98230791, -0.60020423, -0.9962306 , -0.23603959],
         [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]],
 
        [[-0.99890471,  0.99904227, -0.51789087, -0.99995959,  0.04789119],
         [-0.89029807,  0.84119344,  0.97316492, -0.99435395,  0.92399073]],
 
        [[ 0.99975288,  0.91331661,  0.99985558,  0.02976218,  0.61368006],
         [-0.18096282,  0.93361694,  0.38181186, -0.81181109,  0.23601186]]], dtype=float32),
 array([[[-0.89816159, -0.85262525, -0.80174124, -0.81249034,  0.27229077],
         [ 0.99944592, -1.        , -0.99999821,  0.44677779,  0.66885793]],
 
        [[ 0.73549163, -0.99999171, -0.99276799, -0.3467494 ,  0.93305779],
         [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]],
 
        [[ 0.8445127 , -1.        , -0.99997896, -0.675

In [7]:
np_states

(array([[-0.97520906,  0.98924893,  0.97816467, -0.99993235,  0.96553952],
        [-0.98945618,  0.98230791, -0.60020423, -0.9962306 , -0.23603959],
        [-0.89029807,  0.84119344,  0.97316492, -0.99435395,  0.92399073],
        [-0.18096282,  0.93361694,  0.38181186, -0.81181109,  0.23601186]], dtype=float32),
 array([[-0.89816159, -0.85262525, -0.80174124, -0.81249034,  0.27229077],
        [ 0.73549163, -0.99999171, -0.99276799, -0.3467494 ,  0.93305779],
        [ 0.8445127 , -1.        , -0.99997896, -0.67519128,  0.94993401],
        [ 0.87993622, -0.99955827, -0.99886024, -0.61189216, -0.99954116]], dtype=float32))

In [8]:
np_conc_outputs

array([[[-0.90247554,  0.71488017, -0.67150509, -0.69992298, -0.48467708,
         -0.89816159, -0.85262525, -0.80174124, -0.81249034,  0.27229077],
        [-0.97520906,  0.98924893,  0.97816467, -0.99993235,  0.96553952,
          0.99944592, -1.        , -0.99999821,  0.44677779,  0.66885793]],

       [[-0.98945618,  0.98230791, -0.60020423, -0.9962306 , -0.23603959,
          0.73549163, -0.99999171, -0.99276799, -0.3467494 ,  0.93305779],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ]],

       [[-0.99890471,  0.99904227, -0.51789087, -0.99995959,  0.04789119,
          0.8445127 , -1.        , -0.99997896, -0.67519128,  0.94993401],
        [-0.89029807,  0.84119344,  0.97316492, -0.99435395,  0.92399073,
          0.99314833, -0.99999946, -0.9997648 ,  0.42266846,  0.18400697]],

       [[ 0.99975288,  0.91331661,  0.99985558,  0.02976218,  0.61368006,
          0.87993622, -0.9