In a Simple / Basic RNN, it is all about implementing the following equation

$Y_t = f( X_t . W_x +  Y_{t-1} . W_y  + b )$

In [1]:
import numpy as np
import tensorflow as tf
import os
from datetime import datetime

In [2]:
n_inputs = 3
n_neurons = 5
n_steps = 2

In [3]:
# Each row of X corresponds to an instance and each column corresponds to a feature
X = tf.placeholder(tf.float32, [None, n_steps, n_inputs], name='X')
seq_length = tf.placeholder(tf.int32, [None])

basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
outputs, states = tf.nn.bidirectional_dynamic_rnn(basic_cell, basic_cell, X, sequence_length=seq_length, dtype=tf.float32)



In [4]:
now = datetime.utcnow().strftime("%Y-%m-%d-%H:%M:%S")
root_logdir = "tf_logs"
logdir = os.path.join(os.getcwd(),"{}/run-{}".format(root_logdir, now))

file_writer = tf.summary.FileWriter(logdir, tf.get_default_graph())

In [5]:
init = tf.global_variables_initializer()
# Mini-batch
X_batch = np.array([
    # step 0   step 1
    [[0,1,2],[9,8,7]], # instance 0
    [[3,4,5],[0,0,0]], # instance 1
    [[6,7,8],[6,5,4]], # instance 2
    [[9,0,1],[3,2,1]]  # instance 3
])

seq_length_batch = np.array([2,1,2,2])

sess = tf.InteractiveSession()
init.run()
np_outputs, np_states = sess.run([outputs, states], feed_dict={X:X_batch, seq_length:seq_length_batch})
sess.close()
file_writer.close()

In [6]:
np_outputs

(array([[[ 0.62456441,  0.51542926,  0.78852516, -0.30028352,  0.35053119],
         [ 0.99996674,  0.99978018,  0.99912155, -0.98141289,  0.99963123]],
 
        [[ 0.98997939,  0.97457141,  0.98699087, -0.89396745,  0.92034352],
         [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]],
 
        [[ 0.9997806 ,  0.99896324,  0.99927521, -0.9884187 ,  0.99286968],
         [ 0.99889207,  0.99731725,  0.99397218, -0.56042224,  0.9989934 ]],
 
        [[ 0.99874508,  0.79840922, -0.99042952, -0.46883222,  0.98156255],
         [ 0.74849957,  0.59989536,  0.92178011, -0.14657295,  0.71936738]]], dtype=float32),
 array([[[ 0.88217646,  0.84476829,  0.97281945,  0.7660771 ,  0.96930456],
         [ 0.99991047,  0.99959147,  0.99713248, -0.99582374,  0.9973346 ]],
 
        [[ 0.98997939,  0.97457141,  0.98699087, -0.89396745,  0.92034352],
         [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]],
 
        [[ 0.99993819,  0.99970514,  0.99991447, -0.856

In [7]:
np_states

(array([[ 0.99996674,  0.99978018,  0.99912155, -0.98141289,  0.99963123],
        [ 0.98997939,  0.97457141,  0.98699087, -0.89396745,  0.92034352],
        [ 0.99889207,  0.99731725,  0.99397218, -0.56042224,  0.9989934 ],
        [ 0.74849957,  0.59989536,  0.92178011, -0.14657295,  0.71936738]], dtype=float32),
 array([[ 0.88217646,  0.84476829,  0.97281945,  0.7660771 ,  0.96930456],
        [ 0.98997939,  0.97457141,  0.98699087, -0.89396745,  0.92034352],
        [ 0.99993819,  0.99970514,  0.99991447, -0.85645562,  0.9997431 ],
        [ 0.9993546 ,  0.87847453, -0.94623351,  0.36780474,  0.99763197]], dtype=float32))